// Generated by scripts/generate-icons.mjs. Do not edit.
import { forwardRef } from "react";
import { IconBase } from "./IconBase.js";
import type { IconProps } from "../types/IconProps.js";

export const ArrowRightIcon = forwardRef<SVGSVGElement, IconProps>(function ArrowRightIcon(props, ref) {
  return (
    <IconBase ref={ref} {...props}>
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </IconBase>
  );
});
