// Generated by scripts/generate-icons.mjs. Do not edit.
import { forwardRef } from "react";
import { IconBase } from "./IconBase.js";
import type { IconProps } from "../types/IconProps.js";

export const ArrowUpIcon = forwardRef<SVGSVGElement, IconProps>(function ArrowUpIcon(props, ref) {
  return (
    <IconBase ref={ref} {...props}>
      <path d="m5 12 7-7 7 7" />
      <path d="M12 19V5" />
    </IconBase>
  );
});
