// Generated by scripts/generate-icons.mjs. Do not edit.
import { forwardRef } from "react";
import { IconBase } from "./IconBase.js";
import type { IconProps } from "../types/IconProps.js";

export const ArrowLeftIcon = forwardRef<SVGSVGElement, IconProps>(function ArrowLeftIcon(props, ref) {
  return (
    <IconBase ref={ref} {...props}>
      <path d="m12 19-7-7 7-7" />
      <path d="M19 12H5" />
    </IconBase>
  );
});
