// Generated by scripts/generate-icons.mjs. Do not edit.
import { forwardRef } from "react";
import { IconBase } from "./IconBase.js";
import type { IconProps } from "../types/IconProps.js";

export const ArrowDownIcon = forwardRef<SVGSVGElement, IconProps>(function ArrowDownIcon(props, ref) {
  return (
    <IconBase ref={ref} {...props}>
      <path d="M12 5v14" />
      <path d="m19 12-7 7-7-7" />
    </IconBase>
  );
});
