// Generated by scripts/generate-icons.mjs. Do not edit.
import { forwardRef } from "react";
import { IconBase } from "./IconBase.js";
import type { IconProps } from "../types/IconProps.js";

export const BanIcon = forwardRef<SVGSVGElement, IconProps>(function BanIcon(props, ref) {
  return (
    <IconBase ref={ref} {...props}>
      <path d="M4.929 4.929 19.07 19.071" />
      <circle cx="12" cy="12" r="10" />
    </IconBase>
  );
});
