// Generated by scripts/generate-icons.mjs. Do not edit.
import { forwardRef } from "react";
import { IconBase } from "./IconBase.js";
import type { IconProps } from "../types/IconProps.js";

export const ChartBarIcon = forwardRef<SVGSVGElement, IconProps>(function ChartBarIcon(props, ref) {
  return (
    <IconBase ref={ref} {...props}>
      <path d="M3 3v16a2 2 0 0 0 2 2h16" />
      <path d="M7 16h8" />
      <path d="M7 11h12" />
      <path d="M7 6h3" />
    </IconBase>
  );
});
