// Generated by scripts/generate-icons.mjs. Do not edit.
import { forwardRef } from "react";
import { IconBase } from "./IconBase.js";
import type { IconProps } from "../types/IconProps.js";

export const CheckIcon = forwardRef<SVGSVGElement, IconProps>(function CheckIcon(props, ref) {
  return (
    <IconBase ref={ref} {...props}>
      <path d="M20 6 9 17l-5-5" />
    </IconBase>
  );
});
