// Generated by scripts/generate-icons.mjs. Do not edit.
import { forwardRef } from "react";
import { IconBase } from "./IconBase.js";
import type { IconProps } from "../types/IconProps.js";

export const ChevronLeftIcon = forwardRef<SVGSVGElement, IconProps>(function ChevronLeftIcon(props, ref) {
  return (
    <IconBase ref={ref} {...props}>
      <path d="m15 18-6-6 6-6" />
    </IconBase>
  );
});
