// Generated by scripts/generate-icons.mjs. Do not edit.
import { forwardRef } from "react";
import { IconBase } from "./IconBase.js";
import type { IconProps } from "../types/IconProps.js";

export const ChevronsLeftIcon = forwardRef<SVGSVGElement, IconProps>(function ChevronsLeftIcon(props, ref) {
  return (
    <IconBase ref={ref} {...props}>
      <path d="m11 17-5-5 5-5" />
      <path d="m18 17-5-5 5-5" />
    </IconBase>
  );
});
