// Generated by scripts/generate-icons.mjs. Do not edit.
import { forwardRef } from "react";
import { IconBase } from "./IconBase.js";
import type { IconProps } from "../types/IconProps.js";

export const ChevronDownIcon = forwardRef<SVGSVGElement, IconProps>(function ChevronDownIcon(props, ref) {
  return (
    <IconBase ref={ref} {...props}>
      <path d="m6 9 6 6 6-6" />
    </IconBase>
  );
});
