// Generated by scripts/generate-icons.mjs. Do not edit.
import { forwardRef } from "react";
import { IconBase } from "./IconBase.js";
import type { IconProps } from "../types/IconProps.js";

export const ChevronsRightIcon = forwardRef<SVGSVGElement, IconProps>(function ChevronsRightIcon(props, ref) {
  return (
    <IconBase ref={ref} {...props}>
      <path d="m6 17 5-5-5-5" />
      <path d="m13 17 5-5-5-5" />
    </IconBase>
  );
});
