// Generated by scripts/generate-icons.mjs. Do not edit.
import { forwardRef } from "react";
import { IconBase } from "./IconBase.js";
import type { IconProps } from "../types/IconProps.js";

export const ChevronUpIcon = forwardRef<SVGSVGElement, IconProps>(function ChevronUpIcon(props, ref) {
  return (
    <IconBase ref={ref} {...props}>
      <path d="m18 15-6-6-6 6" />
    </IconBase>
  );
});
