// Generated by scripts/generate-icons.mjs. Do not edit.
import { forwardRef } from "react";
import { IconBase } from "./IconBase.js";
import type { IconProps } from "../types/IconProps.js";

export const ClockIcon = forwardRef<SVGSVGElement, IconProps>(function ClockIcon(props, ref) {
  return (
    <IconBase ref={ref} {...props}>
      <path d="M12 6v6l4 2" />
      <circle cx="12" cy="12" r="10" />
    </IconBase>
  );
});
