// Generated by scripts/generate-icons.mjs. Do not edit.
import { forwardRef } from "react";
import { IconBase } from "./IconBase.js";
import type { IconProps } from "../types/IconProps.js";

export const CloudIcon = forwardRef<SVGSVGElement, IconProps>(function CloudIcon(props, ref) {
  return (
    <IconBase ref={ref} {...props}>
      <path d="M17.5 19H9a7 7 0 1 1 6.71-9h1.79a4.5 4.5 0 1 1 0 9Z" />
    </IconBase>
  );
});
