// Generated by scripts/generate-icons.mjs. Do not edit.
import { forwardRef } from "react";
import { IconBase } from "./IconBase.js";
import type { IconProps } from "../types/IconProps.js";

export const GridIcon = forwardRef<SVGSVGElement, IconProps>(function GridIcon(props, ref) {
  return (
    <IconBase ref={ref} {...props}>
      <path d="M12 3v18" />
      <path d="M3 12h18" />
      <rect x="3" y="3" width="18" height="18" rx="2" />
    </IconBase>
  );
});
