// Generated by scripts/generate-icons.mjs. Do not edit.
import { forwardRef } from "react";
import { IconBase } from "./IconBase.js";
import type { IconProps } from "../types/IconProps.js";

export const LoaderIcon = forwardRef<SVGSVGElement, IconProps>(function LoaderIcon(props, ref) {
  return (
    <IconBase ref={ref} {...props}>
      <path d="M21 12a9 9 0 1 1-6.219-8.56" />
    </IconBase>
  );
});
