// Generated by scripts/generate-icons.mjs. Do not edit.
import { forwardRef } from "react";
import { IconBase } from "./IconBase.js";
import type { IconProps } from "../types/IconProps.js";

export const LockIcon = forwardRef<SVGSVGElement, IconProps>(function LockIcon(props, ref) {
  return (
    <IconBase ref={ref} {...props}>
      <rect width="18" height="11" x="3" y="11" rx="2" ry="2" />
      <path d="M7 11V7a5 5 0 0 1 10 0v4" />
    </IconBase>
  );
});
