// Generated by scripts/generate-icons.mjs. Do not edit.
import { forwardRef } from "react";
import { IconBase } from "./IconBase.js";
import type { IconProps } from "../types/IconProps.js";

export const MaximizeIcon = forwardRef<SVGSVGElement, IconProps>(function MaximizeIcon(props, ref) {
  return (
    <IconBase ref={ref} {...props}>
      <path d="M15 3h6v6" />
      <path d="m21 3-7 7" />
      <path d="m3 21 7-7" />
      <path d="M9 21H3v-6" />
    </IconBase>
  );
});
