// Generated by scripts/generate-icons.mjs. Do not edit.
import { forwardRef } from "react";
import { IconBase } from "./IconBase.js";
import type { IconProps } from "../types/IconProps.js";

export const MenuIcon = forwardRef<SVGSVGElement, IconProps>(function MenuIcon(props, ref) {
  return (
    <IconBase ref={ref} {...props}>
      <path d="M4 5h16" />
      <path d="M4 12h16" />
      <path d="M4 19h16" />
    </IconBase>
  );
});
