// Generated by scripts/generate-icons.mjs. Do not edit.
import { forwardRef } from "react";
import { IconBase } from "./IconBase.js";
import type { IconProps } from "../types/IconProps.js";

export const PauseIcon = forwardRef<SVGSVGElement, IconProps>(function PauseIcon(props, ref) {
  return (
    <IconBase ref={ref} {...props}>
      <rect x="14" y="3" width="5" height="18" rx="1" />
      <rect x="5" y="3" width="5" height="18" rx="1" />
    </IconBase>
  );
});
