// Generated by scripts/generate-icons.mjs. Do not edit.
import { forwardRef } from "react";
import { IconBase } from "./IconBase.js";
import type { IconProps } from "../types/IconProps.js";

export const PlusIcon = forwardRef<SVGSVGElement, IconProps>(function PlusIcon(props, ref) {
  return (
    <IconBase ref={ref} {...props}>
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </IconBase>
  );
});
