// Generated by scripts/generate-icons.mjs. Do not edit.
import { forwardRef } from "react";
import { IconBase } from "./IconBase.js";
import type { IconProps } from "../types/IconProps.js";

export const SearchIcon = forwardRef<SVGSVGElement, IconProps>(function SearchIcon(props, ref) {
  return (
    <IconBase ref={ref} {...props}>
      <path d="m21 21-4.34-4.34" />
      <circle cx="11" cy="11" r="8" />
    </IconBase>
  );
});
