// Generated by scripts/generate-icons.mjs. Do not edit.
import { forwardRef } from "react";
import { IconBase } from "./IconBase.js";
import type { IconProps } from "../types/IconProps.js";

export const SmartphoneIcon = forwardRef<SVGSVGElement, IconProps>(function SmartphoneIcon(props, ref) {
  return (
    <IconBase ref={ref} {...props}>
      <rect width="14" height="20" x="5" y="2" rx="2" ry="2" />
      <path d="M12 18h.01" />
    </IconBase>
  );
});
