// Generated by scripts/generate-icons.mjs. Do not edit.
import { forwardRef } from "react";
import { IconBase } from "./IconBase.js";
import type { IconProps } from "../types/IconProps.js";

export const TrendingUpIcon = forwardRef<SVGSVGElement, IconProps>(function TrendingUpIcon(props, ref) {
  return (
    <IconBase ref={ref} {...props}>
      <path d="M16 7h6v6" />
      <path d="m22 7-8.5 8.5-5-5L2 17" />
    </IconBase>
  );
});
