// Generated by scripts/generate-icons.mjs. Do not edit.
import { forwardRef } from "react";
import { IconBase } from "./IconBase.js";
import type { IconProps } from "../types/IconProps.js";

export const TrendingDownIcon = forwardRef<SVGSVGElement, IconProps>(function TrendingDownIcon(props, ref) {
  return (
    <IconBase ref={ref} {...props}>
      <path d="M16 17h6v-6" />
      <path d="m22 17-8.5-8.5-5 5L2 7" />
    </IconBase>
  );
});
