// Generated by scripts/generate-icons.mjs. Do not edit.
import { forwardRef } from "react";
import { IconBase } from "./IconBase.js";
import type { IconProps } from "../types/IconProps.js";

export const UploadIcon = forwardRef<SVGSVGElement, IconProps>(function UploadIcon(props, ref) {
  return (
    <IconBase ref={ref} {...props}>
      <path d="M12 3v12" />
      <path d="m17 8-5-5-5 5" />
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
    </IconBase>
  );
});
