import { styled } from "../stitches";

export const TextStyle = styled("span", {
  color: "$foreground",
  fontFamily: "$ui",
  fontVariantNumeric: "proportional-nums",
  variants: {
    textStyle: {
      display: {
        fontFamily: "$heading",
        fontSize: "$heading",
        fontWeight: "$semibold",
        letterSpacing: "$display",
        lineHeight: "$tight",
        textWrap: "balance",
      },
      headingXl: {
        fontFamily: "$heading",
        fontSize: "$4xl",
        fontWeight: "$semibold",
        letterSpacing: "$display",
        lineHeight: "$tight",
        textWrap: "balance",
      },
      headingLg: {
        fontFamily: "$heading",
        fontSize: "$3xl",
        fontWeight: "$semibold",
        letterSpacing: "$display",
        lineHeight: "$snug",
        textWrap: "balance",
      },
      headingMd: {
        fontFamily: "$heading",
        fontSize: "$2xl",
        fontWeight: "$semibold",
        letterSpacing: "$display",
        lineHeight: "$snug",
        textWrap: "balance",
      },
      headingSm: {
        fontFamily: "$heading",
        fontSize: "$xl",
        fontWeight: "$semibold",
        letterSpacing: "$display",
        lineHeight: "$snug",
        textWrap: "balance",
      },
      title: {
        fontSize: "$lg",
        fontWeight: "$semibold",
        letterSpacing: "$heading",
        lineHeight: "$ui",
        textWrap: "balance",
      },
      bodyLg: { fontSize: "$lg", lineHeight: "$base", textWrap: "pretty" },
      body: { fontSize: "$md", lineHeight: "$base", textWrap: "pretty" },
      bodySm: { fontSize: "$sm", lineHeight: "$base", textWrap: "pretty" },
      label: { fontSize: "$sm", fontWeight: "$medium", lineHeight: "$ui" },
      caption: { fontSize: "$xs", lineHeight: "$base" },
      eyebrow: {
        fontSize: "$xs",
        fontWeight: "$semibold",
        letterSpacing: "$caps",
        lineHeight: "$ui",
        textTransform: "uppercase",
      },
      metricXl: {
        fontSize: "$4xl",
        fontWeight: "$semibold",
        letterSpacing: "$tight",
        lineHeight: "$tight",
        fontVariantNumeric: "tabular-nums lining-nums",
      },
      metricLg: {
        fontSize: "$3xl",
        fontWeight: "$semibold",
        letterSpacing: "$heading",
        lineHeight: "$tight",
        fontVariantNumeric: "tabular-nums lining-nums",
      },
      metric: {
        fontSize: "$xl",
        fontWeight: "$semibold",
        lineHeight: "$ui",
        fontVariantNumeric: "tabular-nums lining-nums",
      },
      code: { fontFamily: "$mono", fontSize: "$sm", lineHeight: "$base" },
      prose: { fontFamily: "$body", fontSize: "$lg", lineHeight: "$relaxed", textWrap: "pretty" },
      quote: {
        fontFamily: "$body",
        fontSize: "$2xl",
        fontStyle: "italic",
        lineHeight: "$base",
        textWrap: "balance",
      },
    },
    emphasis: {
      regular: { fontWeight: "$regular" },
      medium: { fontWeight: "$medium" },
      semibold: { fontWeight: "$semibold" },
      bold: { fontWeight: "$bold" },
    },
    tone: {
      default: { color: "$foreground" },
      muted: { color: "$mutedForeground" },
      accent: { color: "$accentForeground" },
      info: { color: "$infoMutedForeground" },
      success: { color: "$successMutedForeground" },
      warning: { color: "$warningMutedForeground" },
      danger: { color: "$destructive" },
      inverse: { color: "$inverseForeground" },
    },
    numeric: {
      proportional: { fontVariantNumeric: "proportional-nums" },
      tabular: { fontVariantNumeric: "tabular-nums lining-nums" },
    },
    truncate: {
      true: { overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
    },
  },
  defaultVariants: {
    textStyle: "body",
    tone: "default",
  },
});
