import { createStitches, type CSS as StitchesCSS } from "@stitches/react";
import { responsiveBreakpoints } from "./constants/primitives";

export const {
  styled,
  css,
  globalCss,
  keyframes,
  getCssText,
  config,
} = createStitches({
  media: responsiveBreakpoints,
  theme: {
    colors: {
      background: "var(--background)",
      foreground: "var(--foreground)",
      card: "var(--card)",
      cardForeground: "var(--card-foreground)",
      popover: "var(--popover)",
      popoverForeground: "var(--popover-foreground)",
      primary: "var(--primary)",
      primaryForeground: "var(--primary-foreground)",
      secondary: "var(--secondary)",
      secondaryForeground: "var(--secondary-foreground)",
      muted: "var(--muted)",
      mutedForeground: "var(--muted-foreground)",
      accent: "var(--accent)",
      accentForeground: "var(--accent-foreground)",
      surface: "var(--surface)",
      surfaceRaised: "var(--surface-raised)",
      surfaceInset: "var(--surface-inset)",
      inverse: "var(--inverse)",
      inverseForeground: "var(--inverse-foreground)",
      success: "var(--success)",
      successForeground: "var(--success-foreground)",
      successMuted: "var(--success-muted)",
      successMutedForeground: "var(--success-muted-foreground)",
      warning: "var(--warning)",
      warningForeground: "var(--warning-foreground)",
      warningMuted: "var(--warning-muted)",
      warningMutedForeground: "var(--warning-muted-foreground)",
      info: "var(--info)",
      infoForeground: "var(--info-foreground)",
      infoMuted: "var(--info-muted)",
      infoMutedForeground: "var(--info-muted-foreground)",
      destructive: "var(--destructive)",
      destructiveForeground: "var(--destructive-foreground)",
      destructiveMuted: "var(--destructive-muted)",
      destructiveMutedForeground: "var(--destructive-muted-foreground)",
      border: "var(--border)",
      borderStrong: "var(--border-strong)",
      input: "var(--input)",
      ring: "var(--ring)",
    },
    fonts: {
      ui: "var(--font-ui)",
      body: "var(--font-body)",
      heading: "var(--font-heading)",
      mono: "var(--font-mono)",
    },
    fontSizes: {
      xs: "var(--type-size-xs)",
      sm: "var(--type-size-sm)",
      md: "var(--type-size-md)",
      lg: "var(--type-size-lg)",
      xl: "var(--type-size-xl)",
      "2xl": "var(--type-size-2xl)",
      "3xl": "var(--type-size-3xl)",
      "4xl": "var(--type-size-4xl)",
      heading: "var(--type-size-heading)",
    },
    fontWeights: {
      regular: "var(--type-weight-regular)",
      medium: "var(--type-weight-medium)",
      semibold: "var(--type-weight-semibold)",
      bold: "var(--type-weight-bold)",
    },
    lineHeights: {
      tight: "var(--type-leading-tight)",
      snug: "var(--type-leading-heading)",
      ui: "var(--type-leading-ui)",
      base: "var(--type-leading-body)",
      relaxed: "var(--type-leading-relaxed)",
    },
    letterSpacings: {
      tight: "var(--type-tracking-tight)",
      heading: "var(--type-tracking-heading)",
      normal: "var(--type-tracking-normal)",
      caps: "var(--type-tracking-caps)",
    },
    space: {
      1: "var(--space-1)",
      2: "var(--space-2)",
      3: "var(--space-3)",
      4: "var(--space-4)",
      5: "var(--space-5)",
      6: "var(--space-6)",
      7: "var(--space-7)",
      8: "var(--space-8)",
      9: "var(--space-9)",
      10: "var(--space-10)",
      12: "var(--space-12)",
      14: "var(--space-14)",
      16: "var(--space-16)",
      20: "var(--space-20)",
      24: "var(--space-24)",
      32: "var(--space-32)",
    },
    sizes: {
      container: "var(--size-container)",
      containerWide: "var(--size-container-wide)",
      reading: "var(--size-reading)",
      controlCompact: "var(--control-height-compact)",
      controlDefault: "var(--control-height-default)",
      controlComfortable: "var(--control-height-comfortable)",
      hitTarget: "var(--control-hit-target)",
    },
    radii: {
      xs: "var(--radius-xs)",
      sm: "var(--radius-sm)",
      md: "var(--radius-md)",
      lg: "var(--radius-lg)",
      xl: "var(--radius-xl)",
      "2xl": "var(--radius-2xl)",
      pill: "var(--radius-pill)",
      full: "var(--radius-pill)",
    },
    shadows: {
      hairline: "var(--shadow-hairline)",
      soft: "var(--shadow-soft)",
      card: "var(--shadow-card)",
      elevated: "var(--shadow-elevated)",
      focus: "var(--shadow-focus)",
    },
    borderWidths: {
      subtle: "var(--border-weight-subtle)",
      strong: "var(--border-weight-strong)",
    },
    transitions: {
      immediate: "var(--motion-duration-immediate) var(--motion-ease-enter)",
      fast: "var(--motion-duration-fast) var(--motion-ease-standard)",
      base: "var(--motion-duration-base) var(--motion-ease-standard)",
      slow: "var(--motion-duration-slow) var(--motion-ease-standard)",
      enter: "var(--motion-duration-base) var(--motion-ease-enter)",
      exit: "var(--motion-duration-fast) var(--motion-ease-exit)",
    },
    zIndices: {
      base: "var(--layer-base)",
      sticky: "var(--layer-sticky)",
      header: "var(--layer-header)",
      dropdown: "var(--layer-dropdown)",
      overlay: "var(--layer-overlay)",
      modal: "var(--layer-modal)",
      toast: "var(--layer-toast)",
      tooltip: "var(--layer-tooltip)",
    },
  },
});

export type CSS = StitchesCSS<typeof config>;
